# Do you know what this file does?
# Can you explain a bit about CI and the importance of it?

stages:
  - NJ
  - publish

variables:
  DOCKER_IMAGE: docker-registry.prod.williamhill.plc/usd/wdio-selenium-tests-node-12:latest

NJ-GPD:sportsbook:
  stage: NJ
  script:
    - docker run DOCKER_IMAGE npm test
  tags:
    - sample-qa-builder
  variables:
    ENV: GPT
    STATE: NJ
    TAG: "@sportsbook"
  when: manual

push-latest-docker-image:
  stage: publish
  tags:
    - sample-qa-builder
  script:
    - docker build . -t $DOCKER_IMAGE
    - docker push $DOCKER_IMAGE
  only:
    refs:
      - schedules
    variables:
      - $DOCKER_IMAGE_BUILD == "true"
  when: manual
